version: '3.1'

services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
        - "127.0.0.1:5432:5432/tcp"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./SQL/schema:/docker-entrypoint-initdb.d/
      - ./DATA/postgres:/var/lib/postgresql/data    
    